### ISSUE TITLE
Publish `HF Code Autocomplete` to Open VSX

### ISSUE THREAD

**Issue by omhomurlu** [huggingface/llm-vscode#11]
Dear extension author,
Please publish this extension to the Open VSX marketplace.

## Context

Unfortunately, as Microsoft prohibits usages of the Microsoft marketplace by any other products or redistribution of `.vsix` files from it, in order to use VS Code extensions in non-Microsoft products, we kindly ask that you take ownership of the VS Code extension namespace in [Open VSX](https://open-vsx.org/) and publish this extension on Open VSX.

## What is Open VSX? Why does it exist?

Open VSX is a vendor neutral alternative to the MS marketplace used by most other derivatives of VS Code like [VSCodium](https://vscodium.com/), [Gitpod](https://www.gitpod.io), [OpenVSCode](https://github.com/gitpod-io/openvscode-server), [Theia](https://theia-ide.org/)-based IDEs, and so on.

You can read on about Open VSX at the Eclipse Foundation's [Open VSX FAQ](https://www.eclipse.org/legal/open-vsx-registry-faq/).

## How can you publish to Open VSX?

The docs to publish an extension can be found [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions). This process is straightforward and shouldn't take too long. Essentially, you need an authentication token and to execute the `ovsx publish` command to publish your extension. There's also [a doc](https://github.com/open-vsx/publish-extensions/blob/master/docs/direct_publish_setup.md) explaining the whole process with an example GitHub Action workflow.

**Comment by erkkimon** [comment]
Anyway, as a workaround for everyone, go download latest VSIX version from here: https://marketplace.visualstudio.com/items?itemName=HuggingFace.huggingface-vscode

Then go to Hugging Face token management (https://huggingface.co/settings/tokens), create read token and copy it. Then go in VSCodium to extensions tab, click three dots, then "Install from VSIX" and choose the VSIX you downloaded. After that press CMD/CTRL + SHIFT + P, and start writing "Hugging". Then choose "Hugging Face Code: Set API Token" from the list that appeared on the screen if VSIX was installed succesfully, and paste the token here. Now open or create a python file, start to write code and the AI should be writing code for you á la Github Co-Pilot.

If nothing happens or you are unsure is the AI writing code for you Github Co-Pilot or Hugging Face Autocomplete, click CMD/CTRL + SHIFT + U and choose "Hugging Face Code" in the dropdown instead of default "Tasks", and you should see what the VSCodium talks with Hugging Face Code if it does.

**Comment by McPatate** [comment]
https://open-vsx.org/extension/huggingface/huggingface-vscode !
